#This workflow will run automated test on the frontend
name: Automated tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev"]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Check commit messages
      - name: Validate commit messages
        run: wagoid/commitlint-github-action@v6
        working-directory: ./frontend

      # Check css/less/scss
      - name: Validate css/less/scss
        run: npm run lint:css
        working-directory: ./frontend

      # Check typescript and javascript
      - name: Validate typescript and javascript
        run: npm run lint:ts
        working-directory: ./frontend

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Run build
        run: npm run build --if-present
        working-directory: ./frontend
